### ISSUE TITLE
Relative paths (../my/dir) don't appear to work

### ISSUE THREAD

**Issue by jonathandturner** [TypeStrong/atom-typescript#296]
I was looking through the compiler codebase with the plugin and noticed that if you open something like src/server/editorServices.ts, which uses .. in the reference path, that two things happen:

The first is that the plugin can't seem to find the referenced file, though I validated by hand the file is there.

The second is that the editor seems to unexpectedly cut off the first part of the lines, shown in the screenshot:

![screen shot 2015-04-23 at 6 49 57 am](https://cloud.githubusercontent.com/assets/547158/7298550/459ae954-e985-11e4-97d9-b6b5e721304a.png)

**Comment by basarat** [comment]
I am able to reproduce. We've had a similar issue before which I fixed, that had to to do with "BOM" handling. 

Note to self : `session.ts`

**Comment by basarat** [comment]
> unexpectedly cut off the first part of the lines, shown in the screenshot:


Fixed with `v3.2.1` Thanks for reporting :rose: 

> The first is that the plugin can't seem to find the referenced file, though I validated by hand the file is there.

This I couldn't reproduce 

![image](https://cloud.githubusercontent.com/assets/874898/7309833/d5e35294-ea66-11e4-9dd8-f1004bf8ab7e.png)

If you ever feel that atom-typescript's view of the file system is invalid then you can press `cmd+'` to trigger a file cache refresh : https://github.com/TypeStrong/atom-typescript#sync

**Comment by jonathandturner** [comment]
Just updated and the cut-off line is fixed.  Great.  Still seeing the "can't find file" thing, not sure what's going on.  I'm on OS X Yosemite on this laptop.  Not sure what it is.  I'll play with it and if I can come up with a simple repro I'll post that.

**Comment by basarat** [comment]
> I'm on OS X Yosemite on this laptop

I suspect its because of the path using `..\compiler\` instead of `../compiler/`

**Comment by jonathandturner** [comment]
I thought that might be it, but switching didn't seem to fix it.

Oh, you have a cool helper to find the reference.  I like it!  Any thoughts about making it work with .. as well?

![screen shot 2015-04-23 at 7 14 02 pm](https://cloud.githubusercontent.com/assets/547158/7311148/0d4266d2-e9ed-11e4-8cac-ebf4ca703727.png)

**Comment by basarat** [comment]
Can you update and try again : `v4.0.2`

**Comment by jonathandturner** [comment]
Woot.  No repro.  And F12 works.

**Comment by basarat** [comment]
:rose:
